export type Locale = "en" | "bn";

const en = {
  nav: {
    map: "Live map",
    predictor: "Predictor",
    report: "Submit a report",
    language: "বাংলা",
  },
  hero: {
    eyebrow: "Bangladesh community outage map",
    title: "Current Jabe\nKokhon?",
    titleHighlight: "Jabe",
    titleAccent: "",
    description: "Check live reports and likely outage windows for your area.",
    searchLabel: "Choose your area",
    searchPlaceholder: "Search neighborhood, thana or upazila",
    searchHint: "Start broad or choose a known locality such as Mirpur DOHS.",
    methodLink: "How predictions work",
    scroll: "",
    selected: "Your selected area",
    selectedDetail: "Live status and next-24-hour prediction",
    mapLabel: "Live community map",
    mapUpdated: "Reports from the last 30 minutes",
  },
  map: {
    aria: "Interactive map of Bangladesh upazilas, metropolitan thanas and supported local areas",
    allAreas: "64 districts · nationwide",
    country: "Bangladesh",
    freshAreas: "{count} areas have a fresh signal",
    legend: "Map legend",
  },
  status: {
    unknown: "No recent status",
    on: "Current appears on",
    out: "Current appears out",
    unknownDetail: "No qualifying community signal in the last 30 minutes.",
    onDetail: "People nearby recently confirmed electricity is available.",
    outDetail: "At least 10 independent people nearby recently reported an outage.",
    evidence: "community confirmations",
    freshness: "last 30 minutes",
    disclaimer: "Community signal—not an official utility notice.",
  },
  actions: {
    out: "Current is out",
    on: "Current is on",
    history: "Report today’s outages",
    select: "Select this area",
    change: "Change area",
    share: "Share this area",
    copied: "Link copied",
    close: "Close",
    back: "Back",
    continue: "Continue",
    submit: "Submit report",
    done: "Done",
  },
  forecast: {
    eyebrow: "Next 24 hours",
    title: "Community forecast",
    locked: "Not enough local data yet.",
    lockedBody: "A forecast appears after 10 contributors report across at least 3 days.",
    people: "independent contributors",
    events: "timed outage events",
    days: "reporting days",
    recent: "recent evidence",
    live: "Live",
    lockedLabel: "Locked",
    score: "evidence score",
    disclaimer: "Community estimate—not an official utility schedule.",
    unlock: "Help unlock this forecast",
    likely: "Most reported windows",
    alternative: "Other possible windows",
    confidence: "Evidence strength",
    basedOn: "Based on {reports} reports across {days} days",
    verified: "Verified with {days} days of community data",
    historical: "Historically common around this hour",
  },
  report: {
    titleOut: "Report a live outage",
    titleOn: "Confirm the current is on",
    titleHistory: "Report today’s outages",
    privacy: "Anonymous · no phone, email or precise GPS",
    location: "Reporting for",
    liveOutBody:
      "One tap adds a short-lived community signal. We will never show your individual location.",
    liveOnBody:
      "This helps distinguish silence from a real positive signal. Your confirmation expires quickly.",
    countQuestion: "How many times did the current go today?",
    countHelp: "A count is useful even if you do not remember every time.",
    unknownCount: "I don’t remember the count",
    needOneMemory: "Add at least one complete time window when the total count is unknown.",
    rememberQuestion: "Which times do you remember?",
    rememberHelp: "Add all, some, or none. We will never guess missing times.",
    addWindow: "Add another time",
    start: "Went out",
    end: "Came back",
    approximate: "These times are approximate",
    noTimes: "I don’t remember the times",
    successTitle: "Your area just got smarter.",
    successBody: "Thank you. Your anonymous report is now part of the community evidence.",
    received: "Report received",
    dateLabel: "Report date",
    outage: "Outage",
    removeOutage: "Remove outage {number}",
    yesterday: "Report yesterday instead",
    today: "Today",
    yesterdayLabel: "Yesterday",
    error: "That report could not be saved. Please try again.",
  },
  story: {
    eyebrow: "Built for an uncertain grid",
    title: "Less guessing. More planning.",
    body:
      "Load shedding disrupts work, study, sleep and daily life. CurrentJabe turns small anonymous observations into a clearer picture—without pretending community evidence is an official schedule.",
    cards: [
      ["01", "Report", "Tell the map when electricity goes or comes back. It takes seconds."],
      ["02", "Corroborate", "Independent nearby reports strengthen—or contradict—the live signal."],
      ["03", "Forecast", "Once an area earns enough evidence, recurring time windows become visible."],
    ] as const,
  },
  proof: {
    eyebrow: "Evidence, not theatre",
    rulesLabel: "CurrentJabe evidence rules",
    title: "Trust is earned area by area.",
    body:
      "Every forecast shows its sample size, freshness and evidence range. Ten independent local contributors are required before any prediction appears.",
    ten: "10",
    tenLabel: "contributors to unlock",
    thirty: "30m",
    thirtyLabel: "live evidence window",
    zero: "0",
    zeroLabel: "personal details required",
  },
  footer: {
    line: "A community utility built by",
    who: "Who we are",
    privacy: "Privacy",
    method: "Methodology",
    source: "Map data & sources",
    disclaimer:
      "Community estimates can be wrong. Do not rely on CurrentJabe for medical, emergency or safety-critical decisions.",
  },
  area: {
    back: "Bangladesh live map",
    reportsOpen: "Reporting is open nationwide",
    official: "Official provider links",
    unknownProvider: "Provider not confirmed",
    shareTitle: "What should people in {area} expect?",
    country: "Bangladesh",
    reporting: "Community reporting",
    open: "Open",
    providerNote:
      "Provider boundaries can split an upazila. Official links are references; the forecast above remains community-powered.",
  },
  submit: {
    eyebrow: "Anonymous community report",
    title: "Tell your area what happened.",
    body: "No account, phone number or precise GPS. Select an area, then report what you can remember in a few seconds.",
    now: "Right now",
    todayOrYesterday: "Today or yesterday",
    history: "Report outage history",
  },
  common: {
    loading: "Loading community signal…",
    unavailable:
      "The live data service is temporarily unavailable. Status and forecast information may be out of date.",
    noResults: "No matching area yet",
    district: "District",
    upazila: "Upazila / thana",
    provider: "Provider",
    optional: "Optional",
    unknown: "I don’t know",
  },
};

const bn = {
  nav: {
    map: "লাইভ ম্যাপ",
    predictor: "পূর্বাভাস",
    report: "রিপোর্ট দিন",
    language: "English",
  },
  hero: {
    eyebrow: "বাংলাদেশ কমিউনিটি বিদ্যুৎ ম্যাপ",
    title: "কারেন্ট\nকখন যাবে?",
    titleHighlight: "যাবে",
    titleAccent: "",
    description: "আপনার এলাকার লাইভ রিপোর্ট ও সম্ভাব্য বিভ্রাটের সময় দেখুন।",
    searchLabel: "আপনার এলাকা বেছে নিন",
    searchPlaceholder: "পাড়া, থানা বা উপজেলা খুঁজুন",
    searchHint: "থানা দিয়ে শুরু করুন, অথবা মিরপুর ডিওএইচএসের মতো পরিচিত এলাকা বেছে নিন।",
    methodLink: "পূর্বাভাস কীভাবে তৈরি হয়",
    scroll: "",
    selected: "আপনার নির্বাচিত এলাকা",
    selectedDetail: "লাইভ অবস্থা ও পরবর্তী ২৪ ঘণ্টার পূর্বাভাস",
    mapLabel: "লাইভ কমিউনিটি ম্যাপ",
    mapUpdated: "শেষ ৩০ মিনিটের রিপোর্ট",
  },
  map: {
    aria: "বাংলাদেশের উপজেলা, মহানগর থানা ও সমর্থিত স্থানীয় এলাকার ইন্টার‌্যাক্টিভ ম্যাপ",
    allAreas: "৬৪ জেলা · সারা দেশ",
    country: "বাংলাদেশ",
    freshAreas: "{count}টি এলাকায় নতুন সংকেত আছে",
    legend: "ম্যাপের সংকেত",
  },
  status: {
    unknown: "সাম্প্রতিক অবস্থা জানা নেই",
    on: "কারেন্ট আছে বলে মনে হচ্ছে",
    out: "কারেন্ট নেই বলে মনে হচ্ছে",
    unknownDetail: "শেষ ৩০ মিনিটে যথেষ্ট কমিউনিটি তথ্য পাওয়া যায়নি।",
    onDetail: "কাছাকাছি মানুষ সম্প্রতি কারেন্ট থাকার কথা জানিয়েছেন।",
    outDetail: "কাছাকাছি অন্তত ১০ জন আলাদা মানুষ সম্প্রতি কারেন্ট যাওয়ার কথা জানিয়েছেন।",
    evidence: "কমিউনিটি নিশ্চিতকরণ",
    freshness: "শেষ ৩০ মিনিট",
    disclaimer: "এটি কমিউনিটি সংকেত—সরকারি বিদ্যুৎ বিজ্ঞপ্তি নয়।",
  },
  actions: {
    out: "কারেন্ট নেই",
    on: "কারেন্ট আছে",
    history: "আজকের বিদ্যুৎ বিভ্রাট জানান",
    select: "এই এলাকা বেছে নিন",
    change: "এলাকা বদলান",
    share: "এলাকাটি শেয়ার করুন",
    copied: "লিংক কপি হয়েছে",
    close: "বন্ধ করুন",
    back: "পেছনে",
    continue: "এগিয়ে যান",
    submit: "রিপোর্ট জমা দিন",
    done: "শেষ",
  },
  forecast: {
    eyebrow: "পরবর্তী ২৪ ঘণ্টা",
    title: "কমিউনিটি পূর্বাভাস",
    locked: "এখনও যথেষ্ট স্থানীয় তথ্য নেই।",
    lockedBody: "কমপক্ষে ১০ জন ৩টি আলাদা দিনে রিপোর্ট করলে পূর্বাভাস দেখা যাবে।",
    people: "আলাদা অবদানকারী",
    events: "সময়সহ বিভ্রাট",
    days: "রিপোর্টের দিন",
    recent: "সাম্প্রতিক তথ্য",
    live: "লাইভ",
    lockedLabel: "অপেক্ষমাণ",
    score: "তথ্যের স্কোর",
    disclaimer: "কমিউনিটি অনুমান—সরকারি বিদ্যুৎ সময়সূচি নয়।",
    unlock: "পূর্বাভাস চালু করতে সাহায্য করুন",
    likely: "সবচেয়ে বেশি রিপোর্ট হওয়া সময়",
    alternative: "অন্য সম্ভাব্য সময়",
    confidence: "তথ্যের শক্তি",
    basedOn: "{days} দিনে {reports}টি রিপোর্টের ভিত্তিতে",
    verified: "{days} দিনের কমিউনিটি তথ্য দিয়ে যাচাই করা",
    historical: "এই সময়ে আগে প্রায়ই বিভ্রাট হয়েছে",
  },
  report: {
    titleOut: "এখনকার বিভ্রাট জানান",
    titleOn: "কারেন্ট আছে নিশ্চিত করুন",
    titleHistory: "আজকের বিভ্রাট জানান",
    privacy: "নামহীন · ফোন, ইমেইল বা সঠিক GPS নয়",
    location: "যে এলাকার রিপোর্ট",
    liveOutBody:
      "এক ট্যাপে সাময়িক কমিউনিটি সংকেত যোগ হবে। আপনার আলাদা অবস্থান কখনো দেখানো হবে না।",
    liveOnBody:
      "নীরবতা আর সত্যিকারের ইতিবাচক সংকেত আলাদা করতে এটি সাহায্য করে। নিশ্চিতকরণটি দ্রুত মেয়াদোত্তীর্ণ হবে।",
    countQuestion: "আজ কতবার কারেন্ট গেছে?",
    countHelp: "সব সময় মনে না থাকলেও মোট সংখ্যা কাজে লাগে।",
    unknownCount: "মোট সংখ্যা মনে নেই",
    needOneMemory: "মোট সংখ্যা মনে না থাকলে অন্তত একটি সম্পূর্ণ সময় দিন।",
    rememberQuestion: "কোন সময়গুলো মনে আছে?",
    rememberHelp: "সব, কিছু বা একটিও না—যা মনে আছে দিন। হারানো সময় আমরা অনুমান করব না।",
    addWindow: "আরেকটি সময় যোগ করুন",
    start: "কারেন্ট গেছে",
    end: "কারেন্ট এসেছে",
    approximate: "সময়গুলো আনুমানিক",
    noTimes: "সময়গুলো মনে নেই",
    successTitle: "আপনার এলাকার তথ্য আরও ভালো হলো।",
    successBody: "ধন্যবাদ। আপনার নামহীন রিপোর্ট এখন কমিউনিটি তথ্যের অংশ।",
    received: "রিপোর্ট পাওয়া গেছে",
    dateLabel: "রিপোর্টের তারিখ",
    outage: "বিভ্রাট",
    removeOutage: "{number} নম্বর বিভ্রাট সরান",
    yesterday: "গতকালের রিপোর্ট দিন",
    today: "আজ",
    yesterdayLabel: "গতকাল",
    error: "রিপোর্টটি সংরক্ষণ করা যায়নি। আবার চেষ্টা করুন।",
  },
  story: {
    eyebrow: "অনিশ্চিত গ্রিডের জন্য তৈরি",
    title: "কম অনুমান। ভালো পরিকল্পনা।",
    body:
      "লোডশেডিং কাজ, পড়াশোনা, ঘুম আর দৈনন্দিন জীবন ব্যাহত করে। CurrentJabe ছোট ছোট নামহীন পর্যবেক্ষণকে পরিষ্কার চিত্রে পরিণত করে—কমিউনিটি তথ্যকে সরকারি সময়সূচি বলে দাবি না করেই।",
    cards: [
      ["০১", "রিপোর্ট", "কারেন্ট গেলে বা এলে ম্যাপকে জানান। কয়েক সেকেন্ডই যথেষ্ট।"],
      ["০২", "মিল", "কাছাকাছি আলাদা রিপোর্ট লাইভ সংকেতকে শক্তিশালী করে—অথবা ভুল প্রমাণ করে।"],
      ["০৩", "পূর্বাভাস", "যথেষ্ট তথ্য অর্জন করলে নিয়মিত বিভ্রাটের সময় দেখা যায়।"],
    ] as const,
  },
  proof: {
    eyebrow: "প্রমাণ, অভিনয় নয়",
    rulesLabel: "CurrentJabe-এর তথ্যের নিয়ম",
    title: "আস্থা তৈরি হয় এলাকা ধরে।",
    body:
      "প্রতিটি পূর্বাভাসে নমুনা, সাম্প্রতিকতা আর তথ্যের সময়সীমা দেখা যায়। কোনো পূর্বাভাসের আগে ১০ জন আলাদা স্থানীয় অবদানকারী প্রয়োজন।",
    ten: "১০",
    tenLabel: "পূর্বাভাস চালুর অবদানকারী",
    thirty: "৩০মি",
    thirtyLabel: "লাইভ তথ্যের সময়সীমা",
    zero: "০",
    zeroLabel: "ব্যক্তিগত তথ্য প্রয়োজন",
  },
  footer: {
    line: "একটি কমিউনিটি ইউটিলিটি, নির্মাতা",
    who: "আমরা কারা",
    privacy: "গোপনীয়তা",
    method: "পদ্ধতি",
    source: "ম্যাপের তথ্য ও উৎস",
    disclaimer:
      "কমিউনিটি অনুমান ভুল হতে পারে। চিকিৎসা, জরুরি বা নিরাপত্তা-সংক্রান্ত সিদ্ধান্তে CurrentJabe-এর ওপর নির্ভর করবেন না।",
  },
  area: {
    back: "বাংলাদেশ লাইভ ম্যাপ",
    reportsOpen: "সারা দেশে রিপোর্ট নেওয়া হচ্ছে",
    official: "সরকারি প্রদানকারী লিংক",
    unknownProvider: "প্রদানকারী নিশ্চিত নয়",
    shareTitle: "{area}-তে কী হতে পারে?",
    country: "বাংলাদেশ",
    reporting: "কমিউনিটি রিপোর্টিং",
    open: "চালু",
    providerNote:
      "একটি উপজেলার মধ্যে একাধিক প্রদানকারীর এলাকা থাকতে পারে। সরকারি লিংকগুলো তথ্যসূত্র; ওপরের পূর্বাভাসটি কমিউনিটির তথ্যেই তৈরি।",
  },
  submit: {
    eyebrow: "নামহীন কমিউনিটি রিপোর্ট",
    title: "আপনার এলাকায় কী হয়েছে জানান।",
    body: "অ্যাকাউন্ট, ফোন নম্বর বা সঠিক GPS প্রয়োজন নেই। এলাকা বেছে নিয়ে কয়েক সেকেন্ডে যা মনে আছে জানান।",
    now: "এই মুহূর্তে",
    todayOrYesterday: "আজ বা গতকাল",
    history: "বিভ্রাটের সময় জানান",
  },
  common: {
    loading: "কমিউনিটি সংকেত লোড হচ্ছে…",
    unavailable:
      "লাইভ তথ্যসেবা সাময়িকভাবে পাওয়া যাচ্ছে না। অবস্থা ও পূর্বাভাসের তথ্য পুরোনো হতে পারে।",
    noResults: "মিলছে এমন এলাকা পাওয়া যায়নি",
    district: "জেলা",
    upazila: "উপজেলা / থানা",
    provider: "বিদ্যুৎ প্রদানকারী",
    optional: "ঐচ্ছিক",
    unknown: "আমি জানি না",
  },
};

export const copy = { en, bn } as const;
export type Copy = (typeof copy)[Locale];
